# Generated by Django 3.0.2 on 2020-01-17 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.CharField(default='qsi4jgu2ewoh4xxi8bctbl1i3m7bp1mtkj080pzwnhwj73mpz4', max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('game_tag', models.CharField(default='MQHSW', max_length=5, verbose_name='тэг')),
                ('game_name', models.CharField(default='Игра', max_length=50, unique=True, verbose_name='название')),
                ('game_present_cost_min', models.IntegerField(default=200, verbose_name='минимальная стоимость подарка')),
                ('game_present_cost_max', models.IntegerField(default=1000, verbose_name='максимальная стоимость подарка')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='дата начала игры')),
                ('game_timer', models.IntegerField(default=5, verbose_name='длительность игры')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ['pub_date', 'game_name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='электронная почта')),
                ('swo1g5tkykpbg4ir6l122kp449i2vxqvxu9id6gtnemy6g1hu3', models.CharField(max_length=50, verbose_name='ID')),
                ('username', models.CharField(max_length=40, verbose_name='никнейм')),
                ('password', models.CharField(max_length=40, verbose_name='пароль')),
            ],
        ),
        migrations.CreateModel(
            name='Gamer',
            fields=[
                ('gamer_id', models.CharField(default='tqq7ytve42x38o6jpavir9hqdj1z4aub8wu8hs5nf9pnq006uo', max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('gamer_name', models.CharField(max_length=20, verbose_name='имя игрока')),
                ('game', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
            ],
            options={
                'verbose_name': 'Игроки',
                'verbose_name_plural': 'Игрок',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='owner',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='games.User'),
        ),
    ]
