# Generated by Django 3.0.2 on 2020-01-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='swo1g5tkykpbg4ir6l122kp449i2vxqvxu9id6gtnemy6g1hu3',
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='39o26jskca0dtpdba5u0tztuhdo9zobc9ol2g9pi1syxo7uq5e', max_length=50, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.CharField(default='eqoj1c68o0xkvqjnskofmgvymc19km5dydyikewvyhwwq4mvh2', max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_tag',
            field=models.CharField(default='3S8FW', max_length=5, verbose_name='тэг'),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='gamer_id',
            field=models.CharField(default='19w81inz11l6nwqtrwhx8w7izvqtsmi5qa2t6jwg0g6zjimasr', max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
